server:
  port: 8081

logging.level.com.alibaba.nacos.client.naming: WARN

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

ext_val:
  name: "prod env"