spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center

server:
  port: 8081
