spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center

  cloud:
    nacos:
      discovery:
          # 指定nacos server的地址
#          server-addr: localhost:8848
          server-addr: 64.62.166.177:8848
          # 指定namespace
          #namespace: 1c84dc67-f4dd-4fa6-a647-9ebe8d886de8
          namespace: dev_id
          # 指定集群名称
          cluster-name: USA

    sentinel:
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  zipkin:
      base-url: http://localhost:9411/
      discoveryClientEnabled: false
  sleuth:
      sampler:
          # 抽样率，默认是0.1（10%）
          probability: 1.0

ribbon:
  #开启饥饿加载: 在启动的时候便加载所有配置项的应用程序上下文
  eager-load:
    enabled: true
    clients: user-center

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

ext_val:
  name: "chris"


server:
  port: 8081

scut:
  location: gz
  config: mem