spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content-center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        namespace: 1c84dc67-f4dd-4fa6-a647-9ebe8d886de8
        # 指定集群名称
        cluster-name: USA

ribbon:
  #开启饥饿加载: 在启动的时候便加载所有配置项的应用程序上下文
  eager-load:
    enabled: true
    clients: content-center


user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.avistar.contentcenter.configuration.NacosWeightedRule


logging:
  level:
    com.avistar.contentcenter.feignclient.UserCenterFeignClient: debug


server:
  port: 8082
