server:
  port: 9000

---
spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: gateway-center

  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true

  zipkin:
      base-url: http://localhost:9411/
      discoveryClientEnabled: false
  sleuth:
      sampler:
        # 抽样率，默认是0.1（10%）
        probability: 1.0


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


