spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: gateway-center

  cloud:
    nacos:
      discovery:
          # 指定nacos server的地址
          server-addr: localhost:8848
          # 指定namespace
          namespace: 1c84dc67-f4dd-4fa6-a647-9ebe8d886de8
          # 指定集群名称
          cluster-name: USA
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

server:
  port: 9000
