server:
  port: 8082

scut:
  location: gz
  config: mem

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content-center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

  zipkin:
      base-url: http://localhost:9411/
      discoveryClientEnabled: false
  sleuth:
      sampler:
        # 抽样率，默认是0.1（10%）
        probability: 1.0

  cloud:
    sentinel:
          transport:
            # 指定sentinel 控制台的地址
            dashboard: localhost:8080

ribbon:
  #开启饥饿加载: 在启动的时候便加载所有配置项的应用程序上下文
  eager-load:
    enabled: true
    clients: content-center


user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.avistar.content.configuration.NacosWeightedRule


logging:
  level:
    com.avistar.content.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always




