spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: admin-center

  cloud:
    nacos:
      discovery:
          # 指定nacos server的地址
          server-addr: 64.62.166.177:8848
          # 指定namespace
          namespace: dev_id
          # 指定集群名称
          cluster-name: USA

server:
  port: 8090
